### ISSUE TITLE
strange component changes

### ISSUE THREAD

**Issue by randallli** [material-motion/apidiff#28]
[MDC release 84.0.0](https://github.com/material-components/material-components-ios/pull/7311) produced a weird snippet and was called out in this [comment thread](https://github.com/material-components/material-components-ios/pull/7311#discussion_r280543328).

I suspect it is because the commit was not amended properly to use the PR's description. This is not something the API diff too can fix. Unless we want it to ignore the Commit message and use the resolved PR description?

**Comment by jverkoey** [comment]
Ah, this isn't an apidiff issue. It's a bug in the `scripts/release` tool's `notes` command.
